"use client";

import { useState } from "react";
import {
  Heart, FlaskConical, Stethoscope, AlertTriangle, Pill,
  Wifi, Hand, Building2, ChevronDown, ChevronUp, Filter,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const cardShadow = "0 1px 3px rgba(0,0,0,0.4), 0 4px 16px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.04)";

type EventType = "vital" | "lab" | "visit" | "alert" | "medication";
type Severity = "info" | "warning" | "critical";
type Source = "wearable" | "manual" | "provider";

interface ClinicalEvent {
  id: string;
  date: string;
  type: EventType;
  title: string;
  description: string;
  source: Source;
  severity?: Severity;
}

const events: ClinicalEvent[] = [
  { id: "ce1", date: "May 15, 2025", type: "vital", title: "Elevated Resting HR", description: "Resting HR of 84 bpm detected — above baseline of 62 bpm. Continued elevated for 2 hours post-activity.", source: "wearable", severity: "warning" },
  { id: "ce2", date: "May 10, 2025", type: "lab", title: "Lab Results Received", description: "Comprehensive Metabolic Panel results available. HbA1c borderline at 5.8%. All other values within normal range.", source: "provider", severity: "info" },
  { id: "ce3", date: "May 8, 2025", type: "alert", title: "Low SpO2 Alert", description: "Nocturnal SpO2 dipped to 93% at 02:14 AM for 4 minutes. Auto-alert generated by JIVA Smart Band.", source: "wearable", severity: "critical" },
  { id: "ce4", date: "Apr 28, 2025", type: "visit", title: "Telemedicine Consultation", description: "Follow-up with Dr. Ama Owusu. Medication adherence reviewed. Blood pressure within target range. Dietary improvements noted.", source: "provider", severity: "info" },
  { id: "ce5", date: "Apr 20, 2025", type: "medication", title: "Vitamin D Supplementation Started", description: "Started Vitamin D 2000 IU daily. Logged manually by patient following prescription on March 22.", source: "manual", severity: "info" },
  { id: "ce6", date: "Apr 10, 2025", type: "lab", title: "Comprehensive Metabolic Panel", description: "All values normal. Glucose: 94 mg/dL, Total Cholesterol: 188 mg/dL, HbA1c: 5.8% (borderline). Follow-up recommended.", source: "provider", severity: "info" },
  { id: "ce7", date: "Mar 22, 2025", type: "visit", title: "Annual Physical Examination", description: "Annual physical with Dr. Ama Owusu. Recommended increased physical activity and dietary improvements. BMI 25.9 — within normal range.", source: "provider", severity: "info" },
  { id: "ce8", date: "Mar 10, 2025", type: "vital", title: "Irregular HR Pattern", description: "Brief irregular HR pattern detected during sleep — 42 seconds at 02:35 AM. Pattern not repeated on subsequent nights.", source: "wearable", severity: "warning" },
  { id: "ce9", date: "Feb 14, 2025", type: "lab", title: "Chest X-Ray Completed", description: "Clear chest fields. No significant findings. Ordered as part of annual health screening.", source: "provider", severity: "info" },
  { id: "ce10", date: "Jan 20, 2025", type: "medication", title: "Multivitamin Logged", description: "Daily multivitamin supplementation logged by patient.", source: "manual", severity: "info" },
];

const typeConfig: Record<EventType, { icon: React.ComponentType<{ className?: string }>, color: string, label: string }> = {
  vital: { icon: Heart, color: "#f43f5e", label: "Vital" },
  lab: { icon: FlaskConical, color: "#6366f1", label: "Lab" },
  visit: { icon: Stethoscope, color: "#14b8a6", label: "Visit" },
  alert: { icon: AlertTriangle, color: "#f59e0b", label: "Alert" },
  medication: { icon: Pill, color: "#a78bfa", label: "Medication" },
};

const severityConfig: Record<Severity, { color: string; label: string }> = {
  info: { color: "#38bdf8", label: "Info" },
  warning: { color: "#f59e0b", label: "Warning" },
  critical: { color: "#f43f5e", label: "Critical" },
};

const sourceConfig: Record<Source, { icon: React.ComponentType<{ className?: string }>, label: string }> = {
  wearable: { icon: Wifi, label: "Wearable" },
  manual: { icon: Hand, label: "Manual" },
  provider: { icon: Building2, label: "Provider" },
};

const filterTypes: { id: string; label: string }[] = [
  { id: "all", label: "All" },
  { id: "vital", label: "Vitals" },
  { id: "lab", label: "Labs" },
  { id: "visit", label: "Visits" },
  { id: "alert", label: "Alerts" },
  { id: "medication", label: "Medications" },
];

const dateRanges = [
  { id: "30", label: "30 days" },
  { id: "90", label: "90 days" },
  { id: "180", label: "180 days" },
];

export default function ClinicalTimeline() {
  const [typeFilter, setTypeFilter] = useState("all");
  const [dateRange, setDateRange] = useState("180");
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const filtered = events.filter((e) => typeFilter === "all" || e.type === typeFilter);

  return (
    <div className="space-y-4">
      {/* Filters */}
      <Card className="rounded-2xl border border-border/60 bg-card" style={{ boxShadow: cardShadow }}>
        <CardContent className="p-4">
          <div className="flex flex-wrap gap-4 items-center">
            <div className="flex items-center gap-2">
              <Filter className="w-3.5 h-3.5 text-muted-foreground" />
              <span className="text-xs text-muted-foreground font-medium">Type:</span>
              <div className="flex gap-1.5 flex-wrap">
                {filterTypes.map((f) => (
                  <button
                    key={f.id}
                    onClick={() => setTypeFilter(f.id)}
                    className={cn(
                      "px-2.5 py-1 rounded-lg text-xs font-semibold transition-all",
                      typeFilter === f.id
                        ? "bg-[#6366f1]/20 text-[#6366f1] border border-[#6366f1]/40"
                        : "bg-[hsl(240_18%_7%)] text-muted-foreground border border-border/30 hover:text-foreground"
                    )}
                  >
                    {f.label}
                  </button>
                ))}
              </div>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-muted-foreground font-medium">Range:</span>
              <div className="flex gap-1.5">
                {dateRanges.map((r) => (
                  <button
                    key={r.id}
                    onClick={() => setDateRange(r.id)}
                    className={cn(
                      "px-2.5 py-1 rounded-lg text-xs font-semibold transition-all",
                      dateRange === r.id
                        ? "bg-[#14b8a6]/20 text-[#14b8a6] border border-[#14b8a6]/40"
                        : "bg-[hsl(240_18%_7%)] text-muted-foreground border border-border/30 hover:text-foreground"
                    )}
                  >
                    {r.label}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Timeline */}
      <Card className="rounded-2xl border border-border/60 bg-card" style={{ boxShadow: cardShadow }}>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm font-semibold flex items-center gap-2">
            <Stethoscope className="w-4 h-4 text-[#14b8a6]" />
            Clinical Timeline
            <Badge className="text-[10px] px-2 h-4 bg-[hsl(240_12%_12%)] text-muted-foreground border-0 ml-1">
              {filtered.length} events
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="relative">
            {/* Vertical line */}
            <div className="absolute left-5 top-0 bottom-0 w-px bg-border/40" />

            <div className="space-y-0">
              {filtered.map((event, i) => {
                const tc = typeConfig[event.type];
                const sc = event.severity ? severityConfig[event.severity] : null;
                const srcc = sourceConfig[event.source];
                const isExpanded = expandedId === event.id;

                return (
                  <div key={event.id} className="relative pl-12 pb-4 last:pb-0">
                    {/* Node dot */}
                    <div
                      className="absolute left-2.5 w-5 h-5 rounded-full border-2 flex items-center justify-center"
                      style={{
                        backgroundColor: tc.color + "20",
                        borderColor: tc.color + "80",
                        top: "0.75rem",
                      }}
                    >
                      <tc.icon className="w-2.5 h-2.5" style={{ color: tc.color } as React.CSSProperties} />
                    </div>

                    {/* Card */}
                    <button
                      className={cn(
                        "w-full text-left p-3 rounded-xl border transition-all",
                        isExpanded ? "border-opacity-50" : "border-border/30 bg-[hsl(240_18%_7%)] hover:border-border/60"
                      )}
                      style={isExpanded ? {
                        backgroundColor: tc.color + "08",
                        borderColor: tc.color + "40",
                      } : undefined}
                      onClick={() => setExpandedId(isExpanded ? null : event.id)}
                    >
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-1 flex-wrap">
                            <Badge className="text-[10px] h-4 px-2 border-0 capitalize" style={{ backgroundColor: tc.color + "18", color: tc.color }}>
                              {tc.label}
                            </Badge>
                            {sc && (
                              <Badge
                                className={cn("text-[10px] h-4 px-2 border-0", event.severity === "critical" && "animate-pulse")}
                                style={{ backgroundColor: sc.color + "18", color: sc.color }}
                              >
                                {sc.label}
                              </Badge>
                            )}
                            <span className="text-[10px] text-muted-foreground">{event.date}</span>
                          </div>
                          <p className="text-xs font-semibold text-foreground">{event.title}</p>
                          {isExpanded && (
                            <p className="text-xs text-muted-foreground mt-1.5 leading-relaxed">{event.description}</p>
                          )}
                        </div>
                        <div className="flex items-center gap-2 shrink-0">
                          <div className="flex items-center gap-1">
                            <srcc.icon className="w-3 h-3 text-muted-foreground" />
                            <span className="text-[10px] text-muted-foreground">{srcc.label}</span>
                          </div>
                          {isExpanded ? <ChevronUp className="w-3.5 h-3.5 text-muted-foreground" /> : <ChevronDown className="w-3.5 h-3.5 text-muted-foreground" />}
                        </div>
                      </div>
                    </button>
                  </div>
                );
              })}
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
